# Generated by Django 4.1.3 on 2023-09-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(default=True, upload_to='')),
                ('cook', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('publish_date', models.DateField(verbose_name='date publish')),
            ],
        ),
    ]
